### ISSUE TITLE
Offset in InfluxDB\Query\Builder

### ISSUE THREAD

**Issue by BentCoder** [influxdata/influxdb-php#101]
Hi,

Is there a way to use `offset` in `Builder`? I am planning use it for pagination purposes.

Also what is the simples way to get the total value? `SELECT * FROM table` returns many stuff rather than single scalar value such as `23`. Just to replace `$result->getPoints()[0]['count']` which looks ugly.

Thanks

**Comment by BentCoder** [comment]
Although this is a very good library, the issues or the questions hardly attract attention here :)

**Comment by thatside** [comment]
Actually there is a pull request for that since 2016.
https://github.com/influxdata/influxdb-php/pull/56

**Comment by BentCoder** [comment]
This has been addressed in PR above so closing this issue.
