### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by andig** [influxdata/influxdb-php#155]
Currently tied to highest 7:

    "php": "^5.5 || ^7.0",

**Comment by mrbenosborne** [comment]
Has there been any movement on this?

**Comment by zorac** [comment]
The code itself appears to run fine under php 8, but the tests are more of a problem; running them on php 8 requires upgrading to phpunit 8/9, which have minimum php requirements in the 7.x range. I've got a fork with minimal changes to support that, tagged version 1.15.1.2 supports php 8.

**Comment by mrbenosborne** [comment]
> The code itself appears to run fine under php 8, but the tests are more of a problem; running them on php 8 requires upgrading to phpunit 8/9, which have minimum php requirements in the 7.x range. I've got a fork with minimal changes to support that, tagged version 1.15.1.2 supports php 8.

Do you need any manpower or have you finished it?

**Comment by zorac** [comment]
> Do you need any manpower or have you finished it?

It's essentially done. The only change needed by client code is updating the supported PHP versions in `composer.json`. The tagged version does that, plus the minimal changes to get phpunit running without errors. There's one more commit in the branch to have the tests run cleanly on phpunit 9.

**Comment by mrbenosborne** [comment]
> > Do you need any manpower or have you finished it?
> 
> It's essentially done. The only change needed by client code is updating the supported PHP versions in `composer.json`. The tagged version does that, plus the minimal changes to get phpunit running without errors. There's one more commit in the branch to have the tests run cleanly on phpunit 9.

Sounds great, will you be making a PR soon?

**Comment by zorac** [comment]
I've created PR #157 for this.
