### ISSUE TITLE
No access to Point class fields

### ISSUE THREAD

**Issue by undera** [influxdata/influxdb-php#33]
Hi there, thanks for robust library.

I'm facing problem that I have no way to access data stored into Point instance. All fields of Point are private and have no getters. I need that because my code is built around creating array of Point instances in one place, and in other place I need to update some items of array with another Point instances.

Could fields of Point be at least protected or have getters? Having them protected would perfectly satisfy me, I'd inherit from it and add getters myself.

**Comment by thecodeassassin** [comment]
@undera this feature has been added in the 1.2.x release. Thank you for your feedback!

**Comment by undera** [comment]
Thank you very much. I've also just shared my Doctrine DBAL adapter for InfluxDB: https://github.com/undera/doctrine-dbal-influxdb
