### ISSUE TITLE
Paced releases

### ISSUE THREAD

**Issue by skynet** [influxdata/influxdb-php#34]
Would it be possible to deploy regular updates in a similar way with influxdb or telegraf. That'd make us become more confident with the library. It's a shame we do not get enough incentives to switch from the wonderful https://github.com/corley/influxdb-php-sdk to this library,  which is closer to the core influxdb project.

**Comment by thecodeassassin** [comment]
@skynet Who is not giving you enough incentive to switch from that library to this one? They are build with a completely different mindset. This library was build with completely different design goals. The library is also mature enough to work. If there are features you really want in this library then please make feature requests, if there are any bugs then please report it. 

For example @undera submitted a feature request that we are currently implementing.

**Comment by skynet** [comment]
Latest stable release: Sep 22, 2015. That's 1/2 year ago.

**Comment by thecodeassassin** [comment]
@skynet actually it was 21 days ago; i forgot to update the release to 1.1.3 (latest stable tag). There was no real need (before the current feature requests) to add or change something. But this is still an active project. Should you see any features you would like to be added to this library you can either make a PR or a feature request. If we do not see the need to update the library the chance is we probably won't unless there is a nice new feature from InfluxDB, a bug or we take up a TODO. We currently maintain this library with just two people and we are doing the best we can.

**Comment by skynet** [comment]
With 1.2.0 released 3 hours ago I am once again interested to test the library. I believe that you will find needs for improvements as influxDB and this library become more popular.

**Comment by thecodeassassin** [comment]
@skynet let me know what you think. We plan on releasing more often so stay tuned.

**Comment by skynet** [comment]
:100:
