### ISSUE TITLE
Float value in point is sent localized

### ISSUE THREAD

**Issue by brstgt** [influxdata/influxdb-php#58]
This results in an exception like:

HTTP Code 400 {"error":"unable to parse points"} (Class: InfluxDB\Exception)

Fix in InfluxDB\Point:

`/**
     * @param array $fields
     */
    public function setFields($fields)
    {
        foreach ($fields as &$field) {
            if (is_integer($field)) {
                $field = sprintf('%di', $field);
            } elseif (is_string($field)) {
                $field = $this->escapeFieldValue($field);
            } elseif (is_float($field) || is_double($field)) {
                $field = sprintf('%F', $field);
            } elseif (is_bool($field)) {
                $field = ($field ? "true" : "false");
            }
        }

        $this->fields = $fields;
    }`

**Comment by gianarb** [comment]
can you provide a PR and a test for this fix please?
Thanks as lot

**Comment by brstgt** [comment]
Sorry. I am too busy atm and I am not familiar with your test suites. But should be easy to reproduce (and test) by setting a locale that uses "," as decimal separator.
