### ISSUE TITLE
Default timeout is infinite

### ISSUE THREAD

**Issue by dav-is** [influxdata/influxdb-php#78]
Any particular reason why the timeout is set to 0?

https://github.com/influxdata/influxdb-php/blob/master/src/InfluxDB/Client.php#L49

I just encountered a pretty big problem with this. Because there was no timeout, our app was throwing a 504 error and we had no idea what was happening. We had to manually set the timeout to something reasonable so an exception could be called.

**Comment by gianarb** [comment]
Hello @dav-is that's the default value that we took. If you need you can configure the best one for your use case when you create the client:

https://github.com/influxdata/influxdb-php/blob/master/src/InfluxDB/Client.php#L110

Thanks
