### ISSUE TITLE
Waiting for a new release

### ISSUE THREAD

**Issue by salvatorecordiano** [influxdata/influxdb-php#92]
We are waiting for a new release that includes this commit https://github.com/influxdata/influxdb-php/commit/8fcc54417667e9b7c1b7d1cd861e8420f113226a ("Support for Symfony 4").

Thanks

**Comment by Algatux** [comment]
+1

**Comment by gianarb** [comment]
https://github.com/influxdata/influxdb-php/releases/tag/1.14.5

Sorry about the delay! Happy new uear

**Comment by salvatorecordiano** [comment]
Thanks @gianarb !
