### ISSUE TITLE
ResultSet getSeries() doesn't iterate multiple queries 

### ISSUE THREAD

**Issue by harriswong** [influxdata/influxdb-php#94]
ResultSet's `getSeries()` will return only the first element of the `parsedResults`. https://github.com/influxdata/influxdb-php/blob/master/src/InfluxDB/ResultSet.php#L104

To reproduce:
```
$query .= "SELECT * FROM m;"
$query .= "SELECT * FROM m;"
$query .= "SELECT * FROM m;"
$result = $influxDB->query($query);
print_r($result->getSeries());
```
Instead of return 3 series, it will only return one.

PHP 7.0.19-1

**Comment by aldas** [comment]
maybe not to break backwards compatibility just add integer argument for that method to fetch Nth series from result and let it be by default 0 (as currently that method behaves). 

not that beautiful solution but will not break existing code.
